import { Inter, Lexend } from "next/font/google";
import "./globals.css";
import Header from "./components/head/header";
const lexend = Lexend({ subsets: ["latin"] });

export const metadata = {
  title: "Nofour Mart",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={lexend.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
